version: "3.7"
services:

  php-fpm:
    build:
      args:
        phpversion: '${PHP_VERSION:-8.2.0}'
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: '${APP_NAME:-patterns}-php-fpm'
    working_dir: '/var/www'
    volumes:
      - './:/var/www'
      - './docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './docker/php-fpm/php.ini:/usr/local/etc/php/php.ini'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge